# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.batch3.com:
  bharat.org1.batch3.com:
  afroz.org1.batch3.com:
  kumar.org2.batch3.com:
  vazir.org2.batch3.com:

networks:
  byfn:

services:

  orderer.batch3.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.batch3.com
    container_name: orderer.batch3.com
    networks:
      - byfn

  bharat.org1.batch3.com:
    container_name: bharat.org1.batch3.com
    extends:
      file:  base/docker-compose-base.yaml
      service: bharat.org1.batch3.com
    networks:
      - byfn

  afroz.org1.batch3.com:
    container_name: afroz.org1.batch3.com
    extends:
      file:  base/docker-compose-base.yaml
      service: afroz.org1.batch3.com
    networks:
      - byfn

  kumar.org2.batch3.com:
    container_name: kumar.org2.batch3.com
    extends:
      file:  base/docker-compose-base.yaml
      service: kumar.org2.batch3.com
    networks:
      - byfn

  vazir.org2.batch3.com:
    container_name: vazir.org2.batch3.com
    extends:
      file:  base/docker-compose-base.yaml
      service: vazir.org2.batch3.com
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=$SYS_CHANNEL
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=bharat.org1.batch3.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.batch3.com/peers/bharat.org1.batch3.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.batch3.com/peers/bharat.org1.batch3.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.batch3.com/peers/bharat.org1.batch3.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.batch3.com/users/Admin@org1.batch3.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.batch3.com
      - bharat.org1.batch3.com
      - afroz.org1.batch3.com
      - kumar.org2.batch3.com
      - vazir.org2.batch3.com
    networks:
      - byfn
